language: python

python:
  - "3.6.3"
  
cache: pip

install: 
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database testdb1;' -U postgres

script:
  - pytest test_api.py

after_success:
  - coveralls