language: python

python:
  - "3.6.3"

cache: pip

install: 
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres

script:
  - py.test --cov=. tests/test_api.py --cov-config .coveragerc

after_success:
  - coveralls